<?php

namespace AppBundle\Repository;

use AppBundle\Utils\Config;
use AppBundle\Utils\ORM\PaginatorTrait;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Request;

/**
 * AdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminRepository extends EntityRepository
{
    use PaginatorTrait;

    public function paginate(Request $request)
    {
        $keyword = $request->query->get('keyword');
        $currentPage = abs($request->query->getInt('page', 1));
        $qb = $this->createQueryBuilder('a')
            ->join('a.user', 'b')
            ->orderBy('a.name', 'ASC');
        if ($keyword) {
            $orx = $qb->expr()->orX(
                $qb->expr()->like('a.name', ':keyword_like')
            );
            $qb
                ->where($orx)
                ->setParameter('keyword_like', '%'.$keyword.'%');
        }

        $paginator = $this->buildPaginator($qb->getQuery(), $currentPage, Config::PERPAGE);

        return $paginator;
    }
}
