<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Profile;
use AppBundle\Utils\Config;
use AppBundle\Utils\ORM\PaginatorTrait;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Request;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends EntityRepository
{
    use PaginatorTrait;

    public function paginate(Request $request, Profile $currentProfile)
    {
        $keyword = $request->query->get('keyword');
        $currentPage = abs($request->query->getInt('page', 1));
        $qb = $this->createQueryBuilder('a')
            ->join('a.user', 'b')
            ->where('a.id <> :cpid AND b.roles NOT LIKE :crole')
            ->orderBy('a.name', 'ASC')
            ->setParameter('cpid', $currentProfile->getId())
            ->setParameter('crole', '%'.Config::ROLE_SUPER_ADMIN . '%');
        if ($keyword) {
            $orx = $qb->expr()->orX(
                $qb->expr()->like('a.name', ':keyword_like')
            );
            $qb
                ->andWhere($orx)
                ->setParameter('keyword_like', '%'.$keyword.'%');
        }

        $paginator = $this->buildPaginator($qb->getQuery(), $currentPage, Config::PERPAGE);

        return $paginator;
    }
}
