parameters:
    menu_admin:
        dashboard:
            label: Dashboard
            icon: dashboard

        crd_user:
            label: Data User
            icon: user-circle

        adm_setting:
            label: Setting
            icon: cog
